# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('TYPE_INT', 'int'), ('TYPE_FLOAT', 'float'), ('TYPE_STRING', 'string'), ('TYPE_DATETIME', 'datetime'), ('TYPE_IP', 'ip')], default='TYPE_STRING', max_length=45),
        ),
    ]
