# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(default='', max_length=32, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='\u624b\u673a')),
                ('qq', models.CharField(default='', max_length=32, verbose_name='qq')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='\u5165\u804c\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
